# Image builder
FROM maven:3.8.3-openjdk-17 AS build
WORKDIR /app
ADD .  /app
RUN --mount=type=cache,target=/root/.m2 mvn -f /app/pom.xml clean package


# Clean image runtime
FROM eclipse-temurin:17-jre
RUN mkdir /app
WORKDIR /app
COPY --from=build ./app/catalogue/target/catalogue-1.0.0-SNAPSHOT.jar /app
#EXPOSE 8080
CMD ["java", "-jar", "catalogue-1.0.0-SNAPSHOT.jar"]
