# Image builder
FROM maven:3.8.3-openjdk-17 AS build
WORKDIR /app
ADD . /app
RUN --mount=type=cache,target=/root/.m2 mvn -f /app/pom.xml clean package
# TODO: Get project version with `mvn help:evaluate -Dexpression=project.version -q -DforceStdout`

# Clean image runtime
FROM eclipse-temurin:17-jre
RUN mkdir /app
WORKDIR /app
COPY --from=build ./api/target/marketplace-catalog-api.jar /app
#EXPOSE 8080
CMD ["java", "-jar", "marketplace-catalog-api.jar"]
