kumuluzee:
  name: catalogue
  env:
    name: dev
  version: 1.0.0
  server:
    #base-url: http://localhost:8001
    http:
      port: 8001
  openapi:
    enabled: true
    ui:
      enabled: true
  cors-filter:
    annotations:
      catalogue:
        enabled: true
        allow-generic-http-requests: false
        #        allow-origin: "*" # Test only
        allow-origin: "marketplace.bobnar.net"
        allow-subdomains: false
  security:
    keycloak:
      json: '{"realm": "marketplace-test",
              "bearer-only": true,
              "auth-server-url": "https://localhost:8080/auth",
              "ssl-required": "external",
              "resource": "marketplace-catalogue"}'
#  datasources:
#    - jndi-name: jdbc/MarketplaceCatalogueDS
#      #      connection-url: jdbc:postgresql://cornelius.db.elephantsql.com/vqmyhneq
#      #      connection-url: jdbc:postgresql://localhost:15432/marketplace_catalogue_db
#      connection-url: jdbc:postgresql://postgres.n1.local.bobnar.net:15432/marketplace_catalogue_db
#      #      connection-url: jdbc:postgresql://localhost:5432/image-metadata
#      username: marketplace_catalogue_user
#      # vqmyhneq
#      password: vbuJ8as4C4rbpS2RYmx3
#      # OWxoZ6iyUrw4zZzOStHjYw9vhlJmyGby
#      pool:
#        max-size: 4


  health:
    logs:
      enabled: true
      type: readiness
      level: FINE
      period-s: 60
    checks:
      disk-space-health-check:
        threshold: 10000
#      data-source-health-check:
#        - jndi-name: jdbc/MarketplaceCatalogueDS
#          type: liveness
  metrics:
    servlet:
      enabled: true
    web-instrumentation:
      - name: metricsEndpoint
        url-pattern: /metrics/*
      - name: adsEndpoint
        url-pattern: /v1/ads/*










































#kumuluzee:
#  name: catalogue
#  env:
#    name: dev
#  version: 1.0.0
#  server:
#    #base-url: http://localhost:8001
#    http:
#      port: 8001
##  cors-filter:
##    servlet:
##      enabled: true
##      allow-generic-http-requests: false
###        allow-origin: "*" # Test only
##      allow-origin: "marketplace.bobnar.net"
#  openapi:
#    enabled: true
#    ui:
#      enabled: true
#  datasources:
#    - jndi-name: jdbc/MarketplaceCatalogueDS
##      connection-url: jdbc:postgresql://cornelius.db.elephantsql.com/vqmyhneq
##      connection-url: jdbc:postgresql://localhost:15432/marketplace_catalogue_db
#      connection-url: jdbc:postgresql://postgres.n1.local.bobnar.net:15432/marketplace_catalogue_db
##      connection-url: jdbc:postgresql://localhost:5432/image-metadata
#      username: marketplace_catalogue_user
#      # vqmyhneq
#      password: vbuJ8as4C4rbpS2RYmx3
#      # OWxoZ6iyUrw4zZzOStHjYw9vhlJmyGby
#      pool:
#        max-size: 4
##      max-pool-size: 2 # Not working.
##  security:
##    keycloak:
##      json: '{"realm": "marketplace-test",
##              "bearer-only": true,
##              "auth-server-url": "https://localhost:8080/auth",
##              "ssl-required": "external",
##              "resource": "marketplace-catalogue"}'
#  health:
#    checks:
#      disk-space-health-check:
#        threshold: 10000
##        threshold: 1000000
#      data-source-health-check:
#        - jndi-name: jdbc/MarketplaceCatalogueDS
#          type: liveness
##      http-health-check:
##        - connection-url: https://example.org
#
#    logs:
#      enabled: true
#      type: readiness
#      level: FINE
#      period-s: 60
#
#  metrics:
#    servlet:
#      enabled: true
#    web-instrumentation:
#      - name: metricsEndpoint
#        url-pattern: /metrics/*
#      - name: adsEndpoint
#        url-pattern: /v1/ads/*
#
#
#
#  logs:
#    config-file: '<?xml version="1.0" encoding="UTF-8"?>
#                            <Configuration name="comments">
#                                <Appenders>
#                                    <Console name="console" target="SYSTEM_OUT">
#                                        <PatternLayout pattern="%d %p %marker %m %X %ex %n"/>
#                                    </Console>
#                                    <Socket name="logstash" host="0dac2603-ffb0-4e7b-a21b-e96c678c8b02-ls.logit.io"
#                                    port="32606" protocol="udp">
#                                        <JSONLayout complete="false" compact="true" eventEol="true" charset="UTF-8" properties="true"/>
#                                    </Socket>
#                                </Appenders>
#                                <Loggers>
#                                    <!-- Default logger -->
#                                    <Root level="all">
#                                        <AppenderRef ref="console" level="info" />
#                                        <AppenderRef ref="logstash" level="trace" />
#                                    </Root>
#                                </Loggers>
#                            </Configuration>'