# Defaults for local development
kumuluzee:
  name: catalog
  env:
    name: dev
  version: 1.1.4 #${git.build.version}

  server:
#    base-url: http://localhost:8801 # Not needed when working from localhost
    http:
      port: 8801

  openapi:
    enabled: true
    ui:
      enabled: true
  dev:
    scan-libraries: # Related to openapi - need to scan other modules for @Schema annotations
      - marketplace-common

  graphql:
    ui:
      enabled: true
    defaults:
      offset: 0
      limit: 20
#    scanning:
#      optimize: false
#    schema:
#      include-scalars: true
#      include-schema-definition: true
#      include-directives: true
#      include-introspection-types: true

#  security:
#    keycloak:
#      enabled: false
#      json: '{"realm": "marketplace-test",
#              "bearer-only": true,
#              "auth-server-url": "https://localhost:8080/auth",
#              "ssl-required": "external",
#              "resource": "marketplace-catalogue"}'

  datasources:
    - jndi-name: jdbc/MarketplaceCatalogDS
#      connection-url: jdbc:postgresql://n1.ts.bobnar.net:15432/marketplace_catalogue_db
#      connection-url: jdbc:postgresql://localhost:15432/marketplace_catalog_db
      connection-url: jdbc:postgresql://n2.ts.bobnar.net:15432/testing
      username: pgadmin
      password: 7dvJANTz2xdvfGuM7vpS
#      username: marketplace_catalogue_user
#      password: vbuJ8as4C4rbpS2RYmx3
#      password: vbuJ8as4C4rbpS2RYmx3LocalDevelopment
      pool:
        max-size: 4
  grpc:
    server:
      http:
        port: 8081
#      auth:
#        public-key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAnOTgnGBISzm3pKuG8QXMVm6eEuTZx8Wqc8D9gy7vArzyE5QC/bVJNFwlz...
#        issuer: http://id.bobnar.net


  health:
    logs:
      enabled: true
      type: readiness
      level: FINE
      period-s: 60
    checks:
      disk-space-health-check:
        threshold: 10000
#      data-source-health-check:
#        - jndi-name: jdbc/MarketplaceCatalogDS
#          type: liveness

  metrics:
    servlet:
      enabled: true
    web-instrumentation:
      - name: metricsEndpoint
        url-pattern: /metrics/*
      - name: adsEndpoint
        url-pattern: /v1/ads/*
      - name: sellersEndpoint
        url-pattern: /v1/sellers/*
