# Defaults for local development
kumuluzee:
  name: catalog
  env:
    name: dev
  version: 1.1.4 #${git.build.version}

  server:
#    base-url: http://localhost:8801 # Not needed when working from localhost
    http:
      port: 8801

  openapi:
    enabled: true
    ui:
      enabled: true
  dev:
    scan-libraries: # Related to openapi - need to scan other modules for @Schema annotations
      - marketplace-common

  graphql:
    ui:
      enabled: true
    defaults:
      offset: 0
      limit: 20

  datasources:
    - jndi-name: jdbc/MarketplaceCatalogDS
#      connection-url: jdbc:postgresql://n1.ts.bobnar.net:15432/marketplace_catalogue_db
#      connection-url: jdbc:postgresql://localhost:15432/marketplace_catalog_db
#      connection-url: jdbc:postgresql://n2.ts.bobnar.net:15432/testing
      connection-url: jdbc:postgresql://catalog-db.postgres.database.azure.com:5432/marketplace_catalog
#      username: pgadmin
      username: frirsomarketplacecatalogadmin
#      password: 7dvJANTz2xdvfGuM7vpS
      password: 'SL5RiMPnt7BwkWhF6H3YhUgUAzureProductionDeployment'
#      username: marketplace_catalogue_user
#      password: vbuJ8as4C4rbpS2RYmx3
#      password: vbuJ8as4C4rbpS2RYmx3LocalDevelopment
      pool:
        max-size: 4
  grpc:
    server:
      http:
        port: 8081

  logs:
    config-file: '<?xml version="1.0" encoding="UTF-8"?>
                            <Configuration name="comments">
                                <Appenders>
                                    <Console name="console" target="SYSTEM_OUT">
                                        <PatternLayout pattern="%d %p %marker %m %X %ex %n"/>
                                    </Console>
                                    <Socket name="logstash" host="32f52281-cf62-403d-8213-98d4e483f235-ls.logit.io"
                                    port="24380" protocol="udp">
                                        <JSONLayout complete="false" compact="true" eventEol="true" charset="UTF-8" properties="true"/>
                                    </Socket>
                                </Appenders>
                                <Loggers>
                                    <!-- Default logger -->
                                    <Root level="all">
                                        <AppenderRef ref="console" level="info" />
                                        <AppenderRef ref="logstash" level="trace" />
                                    </Root>
                                </Loggers>
                            </Configuration>'

  health:
    logs:
      enabled: true
      type: readiness
      level: FINE
      period-s: 60
    checks:
      disk-space-health-check:
        threshold: 10000
      data-source-health-check:
        - jndi-name: jdbc/MarketplaceCatalogDS
          type: liveness

  metrics:
    servlet:
      enabled: true
    web-instrumentation:
      - name: metricsEndpoint
        url-pattern: /metrics/*
      - name: adsEndpoint
        url-pattern: /v1/ads/*
      - name: sellersEndpoint
        url-pattern: /v1/sellers/*
      - name: brandsEndpoint
        url-pattern: /v1/brands/*
      - name: modelsEndpoint
        url-pattern: /v1/models/*
