kumuluzee:
  name: catalog
  env:
    name: dev
  version: 1.1.2 #${git.build.version}
  server:
    #base-url: http://localhost:8001
    http:
      port: 8002
  dev:
    scan-libraries:
      - marketplace-common
  openapi:
    enabled: true
    ui:
      enabled: true
#  security:
#    keycloak:
#      enabled: false
#      json: '{"realm": "marketplace-test",
#              "bearer-only": true,
#              "auth-server-url": "https://localhost:8080/auth",
#              "ssl-required": "external",
#              "resource": "marketplace-catalogue"}'
  datasources:
    - jndi-name: jdbc/MarketplaceCatalogDS
      #      connection-url: jdbc:postgresql://cornelius.db.elephantsql.com/vqmyhneq
      #      connection-url: jdbc:postgresql://localhost:15432/marketplace_catalogue_db
      connection-url: jdbc:postgresql://postgres.n1.local.bobnar.net:15432/marketplace_catalogue_db
      #      connection-url: jdbc:postgresql://localhost:5432/image-metadata
      username: marketplace_catalogue_user
      password: vbuJ8as4C4rbpS2RYmx3
      pool:
        max-size: 4

  health:
    logs:
      enabled: true
      type: readiness
      level: FINE
      period-s: 60
    checks:
      disk-space-health-check:
        threshold: 10000
#      data-source-health-check:
#        - jndi-name: jdbc/MarketplaceCatalogDS
#          type: liveness
  metrics:
    servlet:
      enabled: true
    web-instrumentation:
      - name: metricsEndpoint
        url-pattern: /metrics/*
      - name: adsEndpoint
        url-pattern: /v1/ads/*
      - name: sellersEndpoint
        url-pattern: /v1/sellers/*
