# Defaults for local development
kumuluzee:
  name: catalog
  env:
    name: dev
  version: 1.1.4 #${git.build.version}

  server:
#    base-url: http://localhost:8801 # Not needed when working from localhost
    http:
      port: 8801

  openapi:
    enabled: true
    ui:
      enabled: true
  dev:
    scan-libraries: # Related to openapi - need to scan other modules for @Schema annotations
      - marketplace-common

#  security:
#    keycloak:
#      enabled: false
#      json: '{"realm": "marketplace-test",
#              "bearer-only": true,
#              "auth-server-url": "https://localhost:8080/auth",
#              "ssl-required": "external",
#              "resource": "marketplace-catalogue"}'

  datasources:
    - jndi-name: jdbc/MarketplaceCatalogDS
      connection-url: jdbc:postgresql://localhost:15432/marketplace_catalog_db
      username: marketplace_catalogue_user
      password: vbuJ8as4C4rbpS2RYmx3LocalDevelopment
      pool:
        max-size: 4

  health:
    logs:
      enabled: true
      type: readiness
      level: FINE
      period-s: 60
    checks:
      disk-space-health-check:
        threshold: 10000
#      data-source-health-check:
#        - jndi-name: jdbc/MarketplaceCatalogDS
#          type: liveness

  metrics:
    servlet:
      enabled: true
    web-instrumentation:
      - name: metricsEndpoint
        url-pattern: /metrics/*
      - name: adsEndpoint
        url-pattern: /v1/ads/*
      - name: sellersEndpoint
        url-pattern: /v1/sellers/*
