kumuluzee:
  name: loader-agent
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8002
    http:
      port: 8002
  openapi:
    enabled: true
    ui:
      enabled: true
  health:
    enabled: true
    checks:
      disk-space-health-check:
        threshold: 1000000
#      http-health-check:
#        - connection-url: https://example.org

    logs:
      enabled: true
      type: readiness
      level: FINE
      period-s: 60

#  metrics:
#    servlet:
#      enabled: true
#    web-instrumentation:
#      - name: metricsEndpoint
#        url-pattern: /metrics/*
#      - name: adsEndpoint
#        url-pattern: /v1/ads/*




  logs:
    config-file: '<?xml version="1.0" encoding="UTF-8"?>
                            <Configuration name="comments">
                                <Appenders>
                                    <Console name="console" target="SYSTEM_OUT">
                                        <PatternLayout pattern="%d %p %marker %m %X %ex %n"/>
                                    </Console>
                                    <Socket name="logstash" host="0dac2603-ffb0-4e7b-a21b-e96c678c8b02-ls.logit.io"
                                    port="32606" protocol="udp">
                                        <JSONLayout complete="false" compact="true" eventEol="true" charset="UTF-8" properties="true"/>
                                    </Socket>
                                </Appenders>
                                <Loggers>
                                    <!-- Default logger -->
                                    <Root level="all">
                                        <AppenderRef ref="console" level="info" />
                                        <AppenderRef ref="logstash" level="trace" />
                                    </Root>
                                </Loggers>
                            </Configuration>'